#
# Copyright (C) 2026 The OrangeFox Recovery Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Screen settings
OF_SCREEN_H := 2400
OF_STATUS_H := 152
OF_STATUS_INDENT_LEFT := 58
OF_STATUS_INDENT_RIGHT := 58
OF_CLOCK_POS := 0
OF_HIDE_NOTCH := 1
OF_ALLOW_DISABLE_NAVBAR := 0
OF_USE_GREEN_LED := 0

# Partition / Device settings
OF_AB_DEVICE_WITH_RECOVERY_PARTITION := 1
OF_DYNAMIC_FULL_SIZE := 9126805504
OF_ENABLE_LPTOOLS := 1
OF_ENABLE_ALL_PARTITION_TOOLS := 1
OF_FORCE_PREBUILT_KERNEL := 1
OF_USE_AIDL_BOOT_CONTROL := 1
OF_USE_DMCTL := 1
OF_OPTIONS_LIST_NUM := 11

# Compatibility & Fixes
OF_NO_RELOAD_AFTER_DECRYPTION := 1
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
OF_NO_MIUI_PATCH_WARNING := 1
OF_DISABLE_MIUI_OTA_BY_DEFAULT := 1
OF_DISPLAY_FORMAT_FILESYSTEMS_DEBUG_INFO := 1

# Filesystem & Data Format
OF_UNBIND_SDCARD_F2FS := 1
OF_WIPE_METADATA_AFTER_DATAFORMAT := 1
OF_FORCE_DATA_FORMAT_F2FS := 1
OF_ENABLE_FS_COMPRESSION := 1
OF_ENABLE_FRP_ADDON := 1

# Compression
OF_USE_LZ4_COMPRESSION := 1

# Maintainer info
OF_MAINTAINER := marcmyworld
